name: work_management
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sidebarx: ^0.16.2
  google_fonts: ^6.1.0
  cloud_firestore: ^4.9.3
  firebase_core: ^2.17.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  go_router: ^11.1.4
  provider: ^6.0.5
  intl:
  lottie: ^2.6.0
  flutter_styled_toast: ^2.2.1
  url_strategy: ^0.2.0

















dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/

